  
name: Publish

on:
  push:
    tags:
    - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Publishing
      run: |
        npm install
        npm test
        npm build
        npm publish
      env:
        CI: true
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
